= connect-java-logging-log4j2

== Description
custom logger for log4j2

This is a custom logger for log4j2 that obeys the rules laid down by the
Connect platform for distributed logging. 

To use it in your log4j2 configuration, add it in packages you should be scanning,
ideally identify it specifically by its classname so it does not scan at all.

The package is `*cd.connect.logging.ConnectJsonLayout*` and it is designed to log to `*stdout*`
 as all distributed loggers are.

[source:xml]
 <Configuration monitorInterval="30" verbose="true" packages="cd.connect.logging">
 
 	<Appenders>
 		<Console name="Console" target="SYSTEM_OUT">
 			<ConnectJsonLayout/>
            <DisableLogsFilter/>    
 		</Console>
 	</Appenders>
 
 	<Loggers>
 
 		<!-- Reduce noise -->
 		<AsyncLogger name="org.springframework" level="info"/>
 		<AsyncLogger name="org.springframework.beans.factory" level="warn"/>
 		<AsyncLogger name="org.apache" level="warn"/>
 		<AsyncLogger name="org.hibernate" level="warn"/>
 		<AsyncLogger name="org.glassfish" level="debug"/>
 		<AsyncLogger name="org.jboss" level="warn"/>
 		<AsyncLogger name="com.amazonaws" level="warn"/>
 
 		<!-- this controls whether each HTTP request is logged (very verbose) -->
 		<AsyncLogger name="jersey-logging" level="trace"/>
 		<AsyncLogger name="cd.connect" level="debug"/>
 
 		<AsyncRoot level="info">
 			<AppenderRef ref="Console"/>
 		</AsyncRoot>
 
 	</Loggers>
 </Configuration>


== Installation Instructions

All of the dependencies of this library (Groovy and Log4j2) are `provided` scope, so you will need
to provide your own dependency versions. 

== Disable Logs Filter

If you add `connect.disable-logs` to your MDC, then it will disable all logs from then on until the 
entry is removed. We recommend using putCloseable so it gets removed from around the context. This
can be useful around things like healthchecks where they do database work and you don't care about
what the logs are saying in the database and generally they are too generic. Regex is a very hard
way to go about killing those kinds of logs.

